# Site settings
title: Elmer Landaverde
email: elmerlandaverde@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://elmerland.com" # the base hostname & protocol for your site
twitter_username: elmerlandaverde
github_username:  elmerland

exclude:
  - "assets/source"
  - Gemfile
  - Gemfile.lock
  - package.json
  - LICENSE
  - README.md
  - "*.git/"
  - ".idea/"
  - ".sass-cache/"
  - "node_modules"
  - "*.o"
  - "**/bin/**"
  - "**/jsx/**"
  - "**/.module-cache/**"
  - "gnu/"
  - "sass/"
  - "jsx/"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Elmer Landaverde"
      email: "elmer@vt.edu"
      permalink: /blog/:title.html

# Build settings
markdown: kramdown

gems:
  - jekyll-last-modified-at
